name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    name: 'Build & Publish'
    runs-on: ubuntu-latest
    steps:
    
      - name: "Run deploy on server"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_CENTRAL }}
          username: ${{ secrets.SERVER_USERNAME_CENTRAL }}
          key: ${{ secrets.SERVER_KEY_CENTRAL }}
          port: ${{ secrets.SERVER_PORT_CENTRAL }}
          script: |
            pwd
            hostname
            whoami
            docker ps -a
